- name: build
  task: rollup --config rollup.config.js

- name: test
  tasks:
    - taskfile lint
    - taskfile spec

- name: lint
  task: xo src/exact-order.js

- name: spec
  task: nyc ava --tap | tap-nyan
